"use client";
import { useClinicInfo } from "@/components/layout/ClinicInfoProvider";
import { ArrowDown, ArrowUpRight, CalendarDays, Clock3, Stethoscope } from "lucide-react";
export default function Hero({ scrollToBooking }: { scrollToBooking: () => void }) {
  const info = useClinicInfo();
  return <header className="border-b border-slate-200 bg-parchment">
    <div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-14 sm:px-8 sm:py-20 lg:grid-cols-[1.15fr_.85fr] lg:gap-20 lg:py-24">
      <div><p className="eyebrow mb-6 flex items-center gap-3"><span className="h-px w-9 bg-gold" />{info.clinicName}</p><h1 className="max-w-2xl text-4xl font-normal leading-[1.2] text-brand-700 sm:text-5xl lg:text-6xl">Эрүүл инээмсэглэл.<br /><span className="text-[#88702a]">Танд зориулсан<br className="hidden sm:block" /> халамж.</span></h1><p className="mt-7 max-w-lg text-base leading-8 text-slate-600">Шүдний эрүүл мэнддээ цаг гаргаарай. Үйлчилгээ, эмч болон өөрт тохирох цагаа сонгон үзлэгийн захиалгаа хялбар бүртгүүлээрэй.</p><div className="mt-9 flex flex-wrap gap-3"><button type="button" onClick={scrollToBooking} className="button-primary px-6 py-3.5">Үзлэгийн цаг авах<ArrowUpRight size={17} /></button><a href="#services" className="button-secondary bg-transparent px-6 py-3.5">Үйлчилгээ үзэх<ArrowDown size={16} /></a></div></div>
      <div className="relative rounded-2xl bg-brand-700 p-7 text-white sm:p-10"><div className="mb-9 flex items-center justify-between border-b border-white/15 pb-6"><div><p className="text-[10px] tracking-[.2em] text-gold">ТАНЫ ДАРААГИЙН ҮЗЛЭГ</p><h2 className="mt-3 font-serif text-2xl font-normal">Цаг авахад хялбар.</h2></div><CalendarDays size={30} strokeWidth={1.2} className="text-gold" /></div><div className="space-y-7">{[{ icon: Stethoscope, label: "Үйлчилгээгээ сонгох", text: "Танд хэрэгтэй тусламж, үйлчилгээ" }, { icon: CalendarDays, label: "Эмч, өдрөө сонгох", text: "Эмчийн боломжит хуваариас" }, { icon: Clock3, label: "Цагаа баталгаажуулах", text: "Мэдээллээ оруулж захиалгаа илгээх" }].map(({ icon: Icon, label, text }, index) => <div key={label} className="flex items-center gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-white/15 text-gold"><Icon size={19} strokeWidth={1.5} /></span><div className="flex-1"><p className="text-sm font-medium">{label}</p><p className="mt-1 text-xs text-brand-100">{text}</p></div><span className="text-xs text-brand-200">0{index + 1}</span></div>)}</div><button type="button" onClick={scrollToBooking} className="mt-9 flex min-h-12 w-full items-center justify-between rounded-xl bg-white px-5 text-sm font-medium text-brand-700 hover:bg-parchment">Захиалгаа эхлүүлэх<ArrowUpRight size={18} /></button></div>
    </div>
  </header>;
}
